### ISSUE TITLE
还是经常丢包，有什么解决办法么？

### ISSUE THREAD

**Issue by cjx1995** [1452206376/ESP32-Paperang-Emulator#2]
Brownout detector was triggered

3秒内输入要测试的STB序号开始打印测试页（1-6）: 
ERROR
ERROR
[INFO]正在打印...
[INFO]共384行
[INFO]打印完成
ERROR
ERROR
[INFO]正在打印...
[INFO]共535行
[INFO]打印完成

**Comment by 1452206376** [comment]
可能是天线被遮挡或者根本没装天线，esp32 wrover i默认使用ipex天线，可以重焊天线旁边的电阻改pcb天线。刚测试打印1000行以上的截图没有error。
下次issue在上一个的下面直接发就行，不必重开一个
